/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import control.GerenciaInterface;

/**
 *
 * @author Marco
 */
public class AreaDeTrabalho extends javax.swing.JFrame {

    private final GerenciaInterface genInter;
    
    public AreaDeTrabalho(GerenciaInterface newGenInter) {
        genInter = newGenInter;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBackgroud = new javax.swing.JLabel();
        mnBarra = new javax.swing.JMenuBar();
        mnMaterias = new javax.swing.JMenu();
        mmRegistrarMeterial = new javax.swing.JMenuItem();
        mmPesquisarMaterial = new javax.swing.JMenuItem();
        mnPessoa = new javax.swing.JMenu();
        mmRegistarPessoa = new javax.swing.JMenuItem();
        mmPesquisarPessoa = new javax.swing.JMenuItem();
        mnTrabalhos = new javax.swing.JMenu();
        mmRegistrarOrcamento = new javax.swing.JMenuItem();
        mmPesquisarOrcamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABM Pinturas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblBackgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ABM-Pinturas.png"))); // NOI18N

        mnMaterias.setText("Materias");

        mmRegistrarMeterial.setText("Registrar Meterial");
        mmRegistrarMeterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmRegistrarMeterialActionPerformed(evt);
            }
        });
        mnMaterias.add(mmRegistrarMeterial);

        mmPesquisarMaterial.setText("Pesquisar Meterial");
        mmPesquisarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmPesquisarMaterialActionPerformed(evt);
            }
        });
        mnMaterias.add(mmPesquisarMaterial);

        mnBarra.add(mnMaterias);

        mnPessoa.setText("Cliente/Fornecedor");

        mmRegistarPessoa.setText("Registrar");
        mmRegistarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmRegistarPessoaActionPerformed(evt);
            }
        });
        mnPessoa.add(mmRegistarPessoa);

        mmPesquisarPessoa.setText("Pesquisar");
        mmPesquisarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmPesquisarPessoaActionPerformed(evt);
            }
        });
        mnPessoa.add(mmPesquisarPessoa);

        mnBarra.add(mnPessoa);

        mnTrabalhos.setText("Trabalhos");

        mmRegistrarOrcamento.setText("Registrar Orçamento");
        mmRegistrarOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmRegistrarOrcamentoActionPerformed(evt);
            }
        });
        mnTrabalhos.add(mmRegistrarOrcamento);

        mmPesquisarOrcamento.setText("Pesquisar Orçamento");
        mmPesquisarOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmPesquisarOrcamentoActionPerformed(evt);
            }
        });
        mnTrabalhos.add(mmPesquisarOrcamento);

        mnBarra.add(mnTrabalhos);

        setJMenuBar(mnBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mmRegistrarMeterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmRegistrarMeterialActionPerformed
        genInter.abrirFormMaterial();
    }//GEN-LAST:event_mmRegistrarMeterialActionPerformed

    private void mmPesquisarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmPesquisarMaterialActionPerformed
        genInter.abrirPesqMaterial();
    }//GEN-LAST:event_mmPesquisarMaterialActionPerformed

    private void mmRegistrarOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmRegistrarOrcamentoActionPerformed
        genInter.abrirFormOrcamento();
    }//GEN-LAST:event_mmRegistrarOrcamentoActionPerformed

    private void mmRegistarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmRegistarPessoaActionPerformed
        genInter.abrirFormPessoa();
    }//GEN-LAST:event_mmRegistarPessoaActionPerformed

    private void mmPesquisarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmPesquisarPessoaActionPerformed
        genInter.abrirPesqPessoa();
    }//GEN-LAST:event_mmPesquisarPessoaActionPerformed

    private void mmPesquisarOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmPesquisarOrcamentoActionPerformed
        genInter.abrirPesqOrcamento();
    }//GEN-LAST:event_mmPesquisarOrcamentoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackgroud;
    private javax.swing.JMenuItem mmPesquisarMaterial;
    private javax.swing.JMenuItem mmPesquisarOrcamento;
    private javax.swing.JMenuItem mmPesquisarPessoa;
    private javax.swing.JMenuItem mmRegistarPessoa;
    private javax.swing.JMenuItem mmRegistrarMeterial;
    private javax.swing.JMenuItem mmRegistrarOrcamento;
    private javax.swing.JMenuBar mnBarra;
    private javax.swing.JMenu mnMaterias;
    private javax.swing.JMenu mnPessoa;
    private javax.swing.JMenu mnTrabalhos;
    // End of variables declaration//GEN-END:variables

}
